List<String> categoryLists = [
  "Anesthesiology",
  "Dermatology",
  "Emergency Medicine",
  "General Medicine",
  "General Surgery",
  "Obstetrics and Gynecology",
  "Ophthalmology",
  "Orthopedics",
  "Otorhinolaryngology (Ear, Nose, and Throat)",
  "Pediatrics",
  "Psychiatry",
  "Radiology",
  "Pathology",
  "Cardiology",
  "Neurology",
  "Nephrology",
  "Endocrinology",
  "Gastroenterology",
  "Hematology",
  "Oncology",
  "Rheumatology",
  "Infectious Diseases",
  "Physical Medicine and Rehabilitation",
  "Pulmonary Medicine",
  "Transfusion Medicine",
  "Nuclear Medicine",
  "Aerospace Medicine",
  "Sports Medicine",
  "Pain Management",
  "Geriatrics",
  "Sleep Medicine",
  "Forensic Medicine",
];

List<String> stateMedicalCouncilLists = [
  "Andhra Pradesh Medical Council",
  "Arunachal Pradesh Medical Council",
  "Assam Medical Council",
  "Bihar Medical Council",
  "Chattisgarh Medical Council",
  "Delhi Medical Council",
  "Goa Medical Council",
  "Gujarat Medical Council",
  "Haryana Medical Council",
  "Himanchal Pradesh Medical Council",
  "Jammu & Kashmir Medical Council",
  "Jharkhand Medical Council",
  "Karnataka Medical Council",
  "Madhya Pradesh Medical Council",
  "Maharashtra Medical Council",
  "Manipur Medical Council",
  "Mizoram Medical Council",
  "Nagaland Medical Council",
  "Orissa Council of Medical Registration",
  "Punjab Medical Council",
  "Rajasthan Medical Council",
  "Sikkim Medical Council",
  "Tamil Nadu Medical Council",
  "Telangana State Medical Council",
  "Travancore Cochin Medical Council, Trivandrum",
  "Tripura State Medical Council",
  "Uttarakhand Medical Council",
  "Uttar Pradesh Medical Council",
  "West Bengal Medical Council",
];
