// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLhoi7hC5mwFLpZKzNkE0CYM7pFw2c-4U',
    appId: '1:252404692069:web:c5e91d3c4c176d3da6028c',
    messagingSenderId: '252404692069',
    projectId: 'fir-test-7f53d',
    authDomain: 'fir-test-7f53d.firebaseapp.com',
    storageBucket: 'fir-test-7f53d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVyXrAHihCj_FhzYFO9bXvS-5XxhpWzkE',
    appId: '1:252404692069:android:422fad9ba3c56927a6028c',
    messagingSenderId: '252404692069',
    projectId: 'fir-test-7f53d',
    storageBucket: 'fir-test-7f53d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPBhq39ECOHWsaicakgLkw88a8adPpZzU',
    appId: '1:252404692069:ios:b48473307f86fd80a6028c',
    messagingSenderId: '252404692069',
    projectId: 'fir-test-7f53d',
    storageBucket: 'fir-test-7f53d.appspot.com',
    iosClientId: '252404692069-rcil3s91pp6fdk7l6c63g2r18ql59mlg.apps.googleusercontent.com',
    iosBundleId: 'com.example.signupLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPBhq39ECOHWsaicakgLkw88a8adPpZzU',
    appId: '1:252404692069:ios:b48473307f86fd80a6028c',
    messagingSenderId: '252404692069',
    projectId: 'fir-test-7f53d',
    storageBucket: 'fir-test-7f53d.appspot.com',
    iosClientId: '252404692069-rcil3s91pp6fdk7l6c63g2r18ql59mlg.apps.googleusercontent.com',
    iosBundleId: 'com.example.signupLogin',
  );
}
